<?php

namespace Movie\ListBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TypeAvisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeAvisRepository extends EntityRepository
{
}
