<?php

namespace Movie\ListBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TypeMovieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeMovieRepository extends EntityRepository
{
}
